apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]

  - apiGroups: [""]
    resources: ["persistentvolumes","storageclasses"]
    verbs: [""]