apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
  - apiGroups: [""]
    verbs: ["create","list"]
    resources: ["pods"]

  - apiGroups: ["apis","extensions"]
    verbs: ["create"]
    resources: ["deployments"]