apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: gautam
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXlRQXF4VkcvZDlMTE80YS9WalNVZmVnRmJpTS9xaFBrNzFlSXljK2dsLzZZCmp4VGxlK0JWR0p1QVhXVzhSVlJ4bHFuNGhiUTdaQlhCNDlUSHd0ZWxyTDhINllCSEFocGQ2aXZLdkticVBXZisKU2RwU0dWUzFkWk42UEhiSU9Dd3ZVZVFXdE1qdmFVK3NIQjVDNURvY1FvVzN0MzVMQ0ZKLzVVNGx6V1o0dHF1ZQpPWFJFNVg2V1M3WTQ0SmNOUTVYNUR3bnRxUWRFMWZteWZGZDQ5WmVlZkJQYXphWU1CbXQyZGNxWkJ6QllRZExyCnVHdHJmV2lHTG00Z0xvTEVRWEdXWGYvSURKWG5zUkVWV0F1L1g1ODVDRFVFai9vbnpvL0xnc29WY2FNM3pTTkcKaDJvSG1BSmVNMGg0T2U1WVdoWjM1N1U4K3pRZE9MNjVHbmcrOGNNTFhRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQjlYbkJtZHVWZndObzcvMjkxSStWZzB2a0JhdGxzT3pTVzRsdWVlelR5T2pFN1A4Y0c2ClB5cElpdjhsdWdmbGpkc3FXa2s1eUxONDlHalllZitVOUNpdGJHSmNEMHphd0FjTlFsTy9BdTBrcWxLUjQ1MWgKcjRYUERwNkdYTUJNUUwzNEtMUHFZaXZldnV5LzhtdmV5aU1hdjR2dlBxMmhIR2FOVXNRaDFGQjc3eHh0b3BYNQpkdmMxVGN0Ymw1YWFudy9wejhibnV3MDh4dHBvdlFMSjArNnZDTThSWkR6eW1oOHJqNlhoTENsS0Y2QllMSUpNCnVxdkFqNGZyY20wdG9HSzFaMFhxa0ZyZWtRSHB6TVdNaWlldUV1RUF0ZGFMR1d3Q0VNeUFOVXZXZnEwTlNVUngKS05BNmxUN3BpeTdaM1lHRzdrUSt5ZTliaTkvTVNuT0JmNm89Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
    - digital signature
    - key encipherment
    - server auth