apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    type frontend
spec:
  containers:
  - name: nginx-containers
  image: nginx
  tolerations:
  - key: "app"
  operator: "Equal"
  value: "blue"
  effect: "NoSchedule"
