apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim