apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: app
    type: frontend
spec:
  template:
    
    metadata:
      name: myapp
      labels:
        app: app
        type: frontend
      spec:
        container: nginx-container
        image: nginx
  replicas: 3
