apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: frontend

  replicas:3
  selector:
    matchLabels:
      type: fronend
