apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - env:
        - name: LOG_HANDLERS
          value: file
      image: kodekloud/event-simulator
      imagePullPolicy: Always
      name: event-simulator
      volumeMounts:
        - mountPath: "/log"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: claim-log-1